// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8m5n_josYx1rGtSzrx4yKGs7BzuzSmn0',
    appId: '1:1081337303914:web:63341e22e36f5da2becb13',
    messagingSenderId: '1081337303914',
    projectId: 'hiring-competitions-76402',
    authDomain: 'hiring-competitions-76402.firebaseapp.com',
    storageBucket: 'hiring-competitions-76402.firebasestorage.app',
    measurementId: 'G-ESWZJSFD0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn91Nt7kDebQVkFeSFCHBNRaLJr9oDhkE',
    appId: '1:1081337303914:android:93de02abcc231d73becb13',
    messagingSenderId: '1081337303914',
    projectId: 'hiring-competitions-76402',
    storageBucket: 'hiring-competitions-76402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO67ubHLOElaFaMIb4PEWoHd-kODRXJ30',
    appId: '1:1081337303914:ios:677e4ae054008f17becb13',
    messagingSenderId: '1081337303914',
    projectId: 'hiring-competitions-76402',
    storageBucket: 'hiring-competitions-76402.firebasestorage.app',
    iosBundleId: 'com.example.hiringCompetitions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO67ubHLOElaFaMIb4PEWoHd-kODRXJ30',
    appId: '1:1081337303914:ios:677e4ae054008f17becb13',
    messagingSenderId: '1081337303914',
    projectId: 'hiring-competitions-76402',
    storageBucket: 'hiring-competitions-76402.firebasestorage.app',
    iosBundleId: 'com.example.hiringCompetitions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8m5n_josYx1rGtSzrx4yKGs7BzuzSmn0',
    appId: '1:1081337303914:web:102a49e258711787becb13',
    messagingSenderId: '1081337303914',
    projectId: 'hiring-competitions-76402',
    authDomain: 'hiring-competitions-76402.firebaseapp.com',
    storageBucket: 'hiring-competitions-76402.firebasestorage.app',
    measurementId: 'G-QMQMQZ4QHK',
  );
}
